### ISSUE TITLE
Unable to Reproduce Paper Code

### ISSUE THREAD

**Issue by zhihuipikaqiu** [liugangcode/MCD#1]
Dear Researcher,

Thank you for your scientific contributions and for sharing them with the community.
When we run the code with the instruction set you provided, the following error repeatedly occurs:

D:\Anaconda\envs\duotiaojian\lib\site-packages\mini_moses\metrics\utils.py:24: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  _mcf.append(_pains, sort=True)['smarts'].values]
bace_b  dataset len 1332 train len 798 val len 267 test len 267 unlabeled len 0
--- Computing intermediate statistics for training for #267 smiles ---
--- End computing intermediate statistics: using 1.28s ---
bace_b  evaluator loaded
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
bace_b  dataset len 1332 train len 798 val len 267 test len 267 unlabeled len 0
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

   | Name             | Type                            | Params
----------------------------------------------------------------------
0  | train_loss       | TrainLossDiscrete               | 0
1  | val_nll          | NLL                             | 0
2  | val_X_kl         | SumExceptBatchKL                | 0
3  | val_E_kl         | SumExceptBatchKL                | 0
4  | val_X_logp       | SumExceptBatchMetric            | 0
5  | val_E_logp       | SumExceptBatchMetric            | 0
6  | test_nll         | NLL                             | 0
7  | test_X_kl        | SumExceptBatchKL                | 0
8  | test_E_kl        | SumExceptBatchKL                | 0
9  | test_X_logp      | SumExceptBatchMetric            | 0
10 | test_E_logp      | SumExceptBatchMetric            | 0
11 | train_metrics    | TrainMolecularMetricsDiscrete   | 0
12 | sampling_metrics | SamplingMolecularMetrics        | 0
13 | model            | Denoiser                        | 158 M
14 | noise_schedule   | PredefinedNoiseScheduleDiscrete | 0
----------------------------------------------------------------------
158 M     Trainable params
0         Non-trainable params
158 M     Total params
632.831   Total estimated model params size (MB)
on fit train iteration: 0
Size of the input features Xdim 8, Edim 5, ydim 3
Computing sampling metrics  ...
Validity over 512 molecules: 55.27% (w/o correction: 58.98%), cover 7 (87.50%) atoms: {'N', 'F', 'O', 'S', 'C', 'Cl', 'Br'}
Number of connected components of 512 molecules: min:1.00 mean:1.00 max:1.00
Error executing job with overrides: ['dataset.task_name=bace_b', 'dataset.guidance_target=Class']
Traceback (most recent call last):
  File "E:\kuosan\duotiaojian\MCD-main\MCD-main\mcd\main.py", line 131, in main
    trainer.fit(model, datamodule=datamodule, ckpt_path=cfg.general.resume)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\trainer\call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 987, in _run
    results = self._run_stage()
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 205, in run
    self.advance()
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 363, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 141, in run
    self.on_advance_end(data_fetcher)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\training_epoch_loop.py", line 295, in on_advance_end
    self.val_loop.run()
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 142, in run
    return self.on_run_end()
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 254, in on_run_end
    self._on_evaluation_epoch_end()
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 334, in _on_evaluation_epoch_end
    call._call_lightning_module_hook(trainer, hook_name)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\pytorch_lightning\trainer\call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "E:\kuosan\duotiaojian\MCD-main\MCD-main\mcd\diffusion_model.py", line 240, in on_validation_epoch_end
    valid_smiles = self.sampling_metrics(samples, all_ys, self.name, self.current_epoch, val_counter=-1, test=False)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\kuosan\duotiaojian\MCD-main\MCD-main\mcd\metrics\molecular_metrics_sampling.py", line 82, in forward
    unique_smiles, all_smiles, all_metrics, targets_log = compute_molecular_metrics(
  File "E:\kuosan\duotiaojian\MCD-main\MCD-main\mcd\analysis\rdkit_functions.py", line 399, in compute_molecular_metrics
    evaluated_res = metrics.evaluate(molecule_list, targets, ensure_connected, active_atoms)
  File "E:\kuosan\duotiaojian\MCD-main\MCD-main\mcd\analysis\rdkit_functions.py", line 125, in evaluate
    dist_metrics['dist/FCD'] = FCDMetric(**kwargs_fcd)(gen=valid, pref=self.stat_ref['FCD'])
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\fcd_torch\fcd.py", line 102, in __call__
    return self.metric(pref, pgen)
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\fcd_torch\fcd.py", line 91, in metric
    return calculate_frechet_distance(
  File "D:\Anaconda\envs\duotiaojian\lib\site-packages\fcd_torch\utils.py", line 167, in calculate_frechet_distance
    raise ValueError("Imaginary component {}".format(m))
ValueError: Imaginary component 8.008264102996831e+29

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

We hope for your assistance and send our best wishes.

**Comment by liugangcode** [comment]
Hi, the error seems to be caused by the `fcd_torch` package. I cannot reproduce it. First, try commenting out the import line:

```python
from fcd_torch import FCD as FCDMetric
```

and set

```python
dist_metrics['dist/FCD'] = 0
```

to see if the error still occurs. If everything else works, you might need to check the package or reinstall it. The tested version of `fcd_torch` is 1.0.7.

**Comment by zhihuipikaqiu** [comment]
> 您好，错误似乎是由`fcd_torch`包引起的。我无法重现它。首先，尝试注释掉导入行：
> 
> ```python
> from fcd_torch import FCD as FCDMetric
> ```
> 
> 并设置
> 
> ```python
> dist_metrics['dist/FCD'] = 0
> ```
> 
> 看看错误是否仍然发生。如果一切正常，您可能需要检查软件包或重新安装。测试的版本`fcd_torch`是 1.0.7。








Thank you very much for your guidance and assistance. We will try to solve this problem based on your suggestions.
Best regards.
